import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Landing from "~/components/Landing/Landing";
import Navbar from "~/components/Navbar";
import About from "~/components/Landing/About";
import Footer from "~/components/Landing/Footer";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"/>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/>  
      </Head>
      <div className="container w-screen h-screen">
          <Navbar/>
          <Landing/>
          <About/>
          <Footer/>
          {/* require image-based landing, information with timeline and explanation, footer */}
          {/* authentication: simple modal form for signup and login */}
          {/* tile-based dashboard form with top, tile for current orders, previous orders, deals, new order button */}
      </div>
    </>
  );
};

export default Home;
