import React from 'react'
import Head from 'next/head'
import Backdrop from '~/components/interface/Backdrop'
import Button from '~/components/interface/Button'
import { useRouter } from 'next/router'

export default function Signup() {

    const router = useRouter()

    const toHome = async () => {
        console.log("hola")
        await router.push("/")
    }

    return (
        <>
            <Head>
                <title>Pizza | Sign Up</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"/>
                <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/>  
            </Head>
            <main className="container w-screen h-screen" onClick={toHome}>
                <div className={`group z-10 fixed top-0 w-screen h-screen bg-rose-900 flex justify-center items-center`}>
                    <div className="w-1/2 h-1/2 bg-white rounded-2xl drop-shadow-2xl hover:drop-shadow-none duration-300 relative overflow-hidden flex flex-row" onClick={e => e.stopPropagation()}>
                        <div className="w-7/12 h-full bg-white p-5 flex flex-col gap-6">
                            <p className="text-6xl font-light">Sign Up To Pizza</p>
                            <hr className="w-48 h-1 mx-10 my-4 bg-gray-100 border-0 rounded md:my-10 dark:bg-slate-600"/>
                            <input type="email" placeholder="Email:" className="border-0 border-b-2 focus:border-0 p-2 focus:border-b-2 outline-0 focus:border-rose-800 duration-300"/>
                            <input type="text" placeholder="Username:" className="border-0 border-b-2 focus:border-0  p-2 focus:border-b-2 outline-0 focus:border-rose-800 duration-300"/>
                            <input type="password" placeholder="Password:" className="border-0 border-b-2 focus:border-0 p-2 focus:border-b-2 outline-0 focus:border-rose-800 duration-300"/>
                            <hr className="w-48 h-1 mx-10 my-4 bg-gray-100 border-0 rounded md:my-10 dark:bg-slate-600"/>
                            <div className="w-11/12 flex justify-end">
                                <button onClick={() => console.log("clicked")} className={`justify-self-end w-1/3 bg-transparent border-rose-700 text-rose-800 text-2xl border-2 p-4 flex justify-center items-center justify-self-end rounded-lg hover:bg-rose-700 hover:text-white duration-300 hover:-translate-y-1 hover:scale-105 flex flex-row gap-3`}>Submit</button>
                            </div>
                        </div>
                        <div className="w-5/12 h-full bg-slate-200 relative flex justify-center items-center">
                            <div className="absolute w-full h-[95%] top-0 left-0 border-b-2 border-dashed border-slate-400"/>
                            <div className="absolute w-[95%] h-full top-0 left-0 border-r-2 border-dashed border-slate-400"/>
                            <div className="absolute w-[5%] h-full top-0 left-0 border-r-2 border-dashed border-slate-400"/>
                            <div className="absolute w-full h-[5%] top-0 left-0 border-b-2 border-dashed border-slate-400"/>
                            <div className="w-10/12 h-5/6 bg-slate-300 rounded-xl shadow-lg hover:shadow-none duration-300 p-2">
                                BRUH
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </>       
    )
}